const SECRET = '6d05954d-ec64-4519-a222-8fa96764fa6e'

const ROLE_ADMINISTRATOR = 'administrator'

const ROLE_SUPPORT = 'support'

const CAMPUS = [
    'VALLEDUPAR',
    'AGUACHICA',
    'CURUMANI',
    'CHIMICHAGUA',
    'JAGUA DE IBIRICO',
]

const AREAS = [
    'DIRECCIÓN GENERAL',
    'SECRETARIA GENERAL',
    'OFICINA JURÍDICA',
    'OFICINA CONTROL INTERNO',
    'ASESOR DIRECCIÓN GENERAL',
    'OFICINA DE SISTEMAS Y TICS',
    'SUBDIRECCIÓN GENERAL ÁREA DE PLANEACIÓN',
    'SUBDIRECCIÓN GENERAL ÁREA DE GESTIÓN AMBIENTAL',
    'SUBDIRECCIÓN GENERAL ÁREA ADMINISTRATIVA Y FINANCIERA',
    'GESTIÓN FINANCIERA',
    'CONTABILIDAD',
    'TESORERIA',
    'PAGADURIA',
    'VENTANILLA ÚNICA',
]

const RAM_MEMORY_TYPES = [
    'DDR2',
    'DDR3',
    'DDR4',
]

const HARD_DRIVE_TYPES = [
    'HDD',
    'SSD'
]

const PROCESSOR_TYPES = [
    'AMD',
    'INTEL'
]

module.exports = {
    SECRET,
    ROLE_ADMINISTRATOR,
    ROLE_SUPPORT,
    CAMPUS,
    AREAS,
    RAM_MEMORY_TYPES,
    HARD_DRIVE_TYPES,
    PROCESSOR_TYPES
}